[package]
name = "hbergv4"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
itertools = "0.14"
polars = { version = "0.46", features = [
    "lazy",
    "dot_diagram",
    "random",
    "parquet",
    #"rows",
    "is_in",
    "fmt",
    "dtype-u8",
    "dtype-u16",
] }
tantivy = "0.24"


[dev-dependencies]
