[package]
name = "hbergv4"
version = "0.1.0"
edition = "2021"


[dependencies]
ahash = "0.8.12"
anyhow = "1.0"
itertools = "0.14"
once_cell = "1.21.3"
polars = { version = "0.46", features = [
    "lazy",
    "parquet",
    "log",
    "strings",
    "round_series",
    "regex",
    "is_in",
    "fmt",
    "dtype-u8",
    "dtype-u16",
    "trigonometry",
    # "performant",
    # "cse",
] }
rayon = "1.10.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
tantivy = "0.24"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"


[dev-dependencies]
