[package]
name = "heisenberg"
version = "0.1.0"
edition = "2024"
authors = ["Sam B"]
license = "MIT"
repository = "https://github.com/SamBroomy/heisenberg"
homepage = "https://github.com/SamBroomy/heisenberg"
readme = "README.md"
description = "Backfill and enrich unstructured location data into structured data using the Geonames Dataset."
categories = ["science::geo"]
keywords = [
    "geonames",
    "polars",
    "location-enrichment",
    "data-processing",
    "geocoding",
    "location",
    "parsing",
]

[dependencies]
ahash = "0.8.12"
anyhow = "1.0"
indicatif = "0.17.11"
itertools = "0.14"
once_cell = "1.21.3"
polars = { version = "0.46", features = [
    "lazy",
    "parquet",
    "log",
    "strings",
    "round_series",
    "regex",
    "is_in",
    "fmt",
    "dtype-u8",
    "dtype-u16",
    "dtype-struct",
    "dtype-categorical",
    "trigonometry",
    "csv",
    "semi_anti_join",
    #"performant",
    "cse",
    #"streaming",
] }
rapidfuzz = "0.5.0"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["stream"] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "fs",
    "macros",
    "io-util",
] }
futures = "0.3"
tantivy = "0.24"
tempfile = "3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
zip = "3"
